spring:
  application:
    name: jh-shop-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/jh_shop_user?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 服务地址
    sentinel:
      transport:
        dashboard: localhost:8080  # Sentinel Dashboard 地址

server:
  port: 8080

feign:
  sentinel:
    enabled: false  # 启用 Feign 的 Sentinel 熔断
  client:
    config:
      default:
        connectTimeout: 5000  # 连接超时
        readTimeout: 5000     # 读取超时

logging:
  level:
    org.springframework: DEBUG
    pers.jhshop.user: DEBUG
    feign: DEBUG                # Feign的调试日志
    com.alibaba.csp.sentinel: DEBUG  # 如果使用Sentinel
    org.springframework.cloud.openfeign: DEBUG